// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKqYwBfyI6tR0F-yQoztEHl0TlIqNfBPw',
    appId: '1:55420909539:web:c109dbb358e611383392d6',
    messagingSenderId: '55420909539',
    projectId: 'lakshya-app-5d1f0',
    authDomain: 'lakshya-app-5d1f0.firebaseapp.com',
    storageBucket: 'lakshya-app-5d1f0.appspot.com',
    measurementId: 'G-1W75ZT7K78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa9oglUO8qQRZwY0eBMLCMOxo7fJUWvkI',
    appId: '1:55420909539:android:6a2193461acf74553392d6',
    messagingSenderId: '55420909539',
    projectId: 'lakshya-app-5d1f0',
    storageBucket: 'lakshya-app-5d1f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJDk43R17eJeI4U51EAGaskwbU90MmJP8',
    appId: '1:55420909539:ios:4be848716a6ac7113392d6',
    messagingSenderId: '55420909539',
    projectId: 'lakshya-app-5d1f0',
    storageBucket: 'lakshya-app-5d1f0.appspot.com',
    iosBundleId: 'com.example.lakshyaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJDk43R17eJeI4U51EAGaskwbU90MmJP8',
    appId: '1:55420909539:ios:0069037dbbbcbba93392d6',
    messagingSenderId: '55420909539',
    projectId: 'lakshya-app-5d1f0',
    storageBucket: 'lakshya-app-5d1f0.appspot.com',
    iosBundleId: 'com.example.lakshyaApp.RunnerTests',
  );
}
